# Site settings
title: Aidan's Blog
url: "http://www.aidandai.com" 
baseurl:
keyword: >
  文桥的个人博客,文桥,Aidan Dai, AidanDai, Aidan,Aidan的自留地,文桥的个人网站 
description: >
  Stay hungry, stay foolish! - http://www.aidandai.com(专注前端，记录前端路上的点点滴滴！)

# Your information
#email: aidandai@126.com
author: Aidan Dai
avatar: "/asset/images/aidan.jpg"
profile: Stay hungry, stay foolish!
#twitter_username: twitter_username
github_username:  AidanDai

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: aidandai  
# get one: http://duoshuo.com/create-site/

permalink: /archives/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge